GET https://workspaces-ws-njzxl-app1.us10.trial.applicationstudio.cloud.sap/employee/Employees HTTP/1.1
cookie: workspaces-ws-fhcls_WSR_SESSIONID=0ewVf7dgVs5brTAA9UNPX/rXJJ80bv01NNBnyhOTcti2LA/7A4G37dzjHmbx+ZH4mUt3HqOuuv7wGaXSmJPv5Q==; country=IN; notice_behavior=implied,us; workspaces-ws-njzxl_WSR_SESSIONID=70Z5AWk/uMnaWB5boAYAoKHTnhadAMrr13o1JaHOmDdbPELcWWBl3ToNZLTlSOJZGhbeXTRFopKdHerXC5Mfhg== 

###

POST https://workspaces-ws-njzxl-app1.us10.trial.applicationstudio.cloud.sap/employee/Employees HTTP/1.1
cookie:  workspaces-ws-fhcls_WSR_SESSIONID=0ewVf7dgVs5brTAA9UNPX/rXJJ80bv01NNBnyhOTcti2LA/7A4G37dzjHmbx+ZH4mUt3HqOuuv7wGaXSmJPv5Q==; country=IN; notice_behavior=implied,us; workspaces-ws-njzxl_WSR_SESSIONID=70Z5AWk/uMnaWB5boAYAoKHTnhadAMrr13o1JaHOmDdbPELcWWBl3ToNZLTlSOJZGhbeXTRFopKdHerXC5Mfhg==
Content-Type: application/json

{
    "ID": 5,
    "Name": "Man",
    "Age": 25
}
    
###

